### ISSUE TITLE
UI Router Considerations

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/rupert#13]
David,

Just wrote up the following wiki entry on UI Router templates: https://github.com/RupertJS/rupert/wiki/Cookbook:-Angular-UI-Router-Templates. Please "QA" it when you get the chance.

While writing it, I ran into a concern. Consider there needs to be multiple template files (`safari-template.jade` and `arctic-template.jade`) in a "feature" directory called `zoo`. It appears (and I could be wrong here) that Rupert can only reference the `$templateCache` of key 'zoo', causing ambiguity since there are > 1 templates.

Would it be worthwhile for me to write up a PR that sets/gets $templateCache as named more granularly (`zoo-arctic` and `zoo-safari` as key names, for example) or can you make a case for the 1 template per feature directory implementation?

**Comment by DavidSouther** [comment]
Merged the PR for the updated README. Thanks so many bunches!

**Comment by MatthewVita** [comment]
:+1:
