### ISSUE TITLE
Conventions for Alpha

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/rupert#21]
David,

For the alpha release, do we want to consider changing up project conventions to something like:
rupert-frontend-* (angular, knockout, react, etc)
rupert-backend-* (express, hapi, etc)
rupert-data-* (mongoose, etc)
rupert-compile-* (es6, etc)
rupert-tutorial-* (demo app, ng phonecat)

...we could keep the "base" projects (stassets, rupert-grunt, etc) as is or call them rupert-core-*

thoughts?

**Comment by MatthewVita** [comment]
Works for me. One more thing... should rupert-cashier be a plugin since it's really not supplying "core" functionality?

**Comment by DavidSouther** [comment]
Haven't decided. It doesn't exist yet, so no worries on naming issues. It would be pretty unique if Rupert had that, which makes me lean towards top level. But again, that's a decision for later.

**Comment by DavidSouther** [comment]
I'm closing this, as the remaining issues in teh checklist are not critical.
