### ISSUE TITLE
Rupert Windows Issue

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/rupert#28]
David,

Just tested it and I see that Rupert works just fine on Windows aside from one small bug... basically when I have a `/src/client/person/template.html` ... I get the following:

![bug](http://i.imgur.com/IUJYAQh.png)

...one can do `window.Templates['/person']`, but clearly that's hacky

**Comment by DavidSouther** [comment]
I'd noticed that a while back, and thought it'd gotten fixed. Let me dig around a moment. Also, please refile in `stassets`.

**Comment by MatthewVita** [comment]
added to stassets here: https://github.com/RupertJS/stassets/issues/32
