### ISSUE TITLE
Plugin SVG Question

### ISSUE THREAD

**Issue by MatthewVita** [RupertJS/rupert#29]
More of a general question... how do I properly embed the SVG (in a readme) you recently handed off to me?

see my failed attempt here: https://raw.githubusercontent.com/MatthewVita/rupert-plugin-knockout/master/README.md

**Comment by DavidSouther** [comment]
```
![Rupert Knockout](https://cdn.rawgit.com/DavidSouther/rupert/master/src/assets/logos/Rupert_Knockout.svg)
```

![Rupert
Knockout](https://cdn.rawgit.com/DavidSouther/rupert/master/src/assets/logos/Rupert_Knockout.svg)

**Comment by MatthewVita** [comment]
thx
